name: ${pom.artifactId}
version: ${pom.version}
depend: [Votifier]
description: ${pom.description}

main: net.omniscimus.universalvotes.UniversalVotes
database: false

commands:
   vote:
      description: The main command for UniversalVotes.
      usage: /vote <add|get|set|fake>
